### ISSUE TITLE
(feature) Add model validations using JOI

### ISSUE THREAD

**Issue by msantang78** [ArgenissSoftware/jared-backend#34]
https://github.com/hapijs/joi

If validation fails it must return the fields error object in the response
For example:
`
{
  errorInfo: 'Validation Error',
  fieldsErrors: {
    name: [
      'Must be a string'
    ]
  },
  data: {}
}
`

**Comment by tinchoaguer** [comment]
Should the validations be added to the "User" and "Client" entities?
Are there specific validations for each field?

**Comment by msantang78** [comment]
Exactly, we must validate each field of the models

**Comment by tinchoaguer** [comment]
These are the validations that were added to the models:

const userSchema = Joi.object().keys({
    username: Joi.string().min(3).max(15).required(),
    email: argenissEmail.required(),
    password: Joi.string().min(6).max(8).required(),
    active: Joi.boolean().truthy(['yes','1','true']).falsy('no','0','false'),
    admin: Joi.boolean().truthy(['yes','1','true']).falsy('no','0','false'),
    name: Joi.string().min(2).max(50),
    surname: Joi.string().min(2).max(50),
    cuil: Joi.string().min(11).max(11),
    passport: Joi.string().min(2).max(50),
    visa: Joi.date(),
    address: Joi.string().min(3).max(50),
    phone: Joi.number(),
    cellphone: Joi.number(),
    birthday: Joi.date().min('01-01-1890').less('now'),
    skype: Joi.string().min(3).max(50),
    childrenCount: Joi.number().min(0),
    career: Joi.string().min(3).max(50),
    status: Joi.string().min(3).max(50),
    startWorkDate: Joi.date().max('now'),
    alarmCode: Joi.string().min(3).max(50),
    githubID: Joi.string().min(3).max(50),
    relation: Joi.any().valid( ['freelance', 'hired'])
});

const clientSchema = Joi.object().keys({
    name: Joi.string().min(3).max(100).required(),
    contactName: Joi.string().min(3).max(50),
    email: commonEmail,
    address: Joi.string().min(3).max(50),
    url: url,
    active: Joi.boolean().truthy(['yes','1','true']).falsy('no','0','false')
});

Any suggestion or comment is welcome.

**Comment by tinchoaguer** [comment]
### This is an example of a response with validations errors messages:
    "status": 500,
    "errorInfo": {
        "isJoi": true,
        "name": "ValidationError",
        "details": [
            {
                "message": "\"email\" with value \"martin@gmail.com\" fails to match the required pattern: /^[a-zA-Z0-9_.+-]+@(?:(?:[a-zA-Z0-9-]+\\.)?[a-zA-Z]+\\.)?(argeniss)\\.com$/",
                "path": [
                    "email"
                ],
                "type": "string.regex.base",
                "context": {
                    "pattern": {},
                    "value": "martin@gmail.com",
                    "key": "email",
                    "label": "email"
                }
            },
            {
                "message": "\"password\" length must be at least 6 characters long",
                "path": [
                    "password"
                ],
                "type": "string.min",
                "context": {
                    "limit": 6,
                    "value": "ma",
                    "key": "password",
                    "label": "password"
                }
            },
            {
                "message": "\"active\" must be a boolean",
                "path": [
                    "active"
                ],
                "type": "boolean.base",
                "context": {
                    "key": "active",
                    "label": "active"
                }
            }
        ],
        "_object": {
            "username": "martin",
            "email": "martin@gmail.com",
            "password": "ma",
            "active": "yees",
            "admin": "0",
            "name": "martin",
            "surname": "aguer",
            "cuil": "20268096656",
            "passport": "123131",
            "visa": "01/01/2018",
            "address": "Casiano Calderón 1902",
            "phone": "1",
            "cellphone": "1",
            "birthday": "1978-11-01",
            "skype": "tinchoaguer",
            "childrenCount": "0",
            "career": "developer",
            "status": "123",
            "startWorkDate": "2017-07-19",
            "alarmCode": "1234",
            "githubID": "234",
            "relation": "freelance"
        }
    },
    "data": {}
}

**Comment by msantang78** [comment]
Excellent!
