### ISSUE TITLE
Client Rest actions

### ISSUE THREAD

**Issue by jchiavaro** [ArgenissSoftware/jared-backend#4]
We need to add the following actions to the clients resource:
* POST /clients with the request json
* GET /clients - returns {"clients": [{}, {} ... {}]}
* GET /clients/<client_id> - returns {"client_data": {}}
*  PUT /clients/<client_id> with the request json
* DELETE /clients/<client_id>

**Comment by rodrigoargeniss** [comment]
Merged to master branch
